### ISSUE TITLE
Incorrect indentation

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/docs-choreo-dev#26]
**Description:**
Refer the below image in [1]. Corresponding .md file is [2]. Without indentation it doesn't look like it belongs to the bullet point of `GitHub`

<img width="852" alt="image" src="https://user-images.githubusercontent.com/16300038/115713489-af35f100-a393-11eb-8cab-de656942b162.png">

[1] https://docs.dv.choreo.dev/integrations/integration-concepts/
[2] https://github.com/wso2/docs-choreo-dev/blob/dev/en/docs/integrations/integration-concepts.md

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nashaath** [comment]
Fixed via https://github.com/wso2/docs-choreo-dev/pull/28.
