### ISSUE TITLE
Create documentaton for expression syntax

### ISSUE THREAD

**Issue by shaniR** [wso2/docs-choreo-dev#37]
**Description:**
Currently a doc is not available explaining the syntax. We need a doc with the relevant information from the developers.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shaniR** [comment]
https://github.com/wso2/docs-choreo-dev/pull/45

**Comment by anupama-pathirage** [comment]
Closing this issue as it is already tracked via  https://github.com/wso2-enterprise/choreo/issues/3734
