### ISSUE TITLE
Images are broken

### ISSUE THREAD

**Issue by shaniR** [wso2/docs-choreo-dev#47]
**Description:**
Currently, the image links in the documentation is broken. Seems like it is broken with the change https://github.com/wso2/docs-choreo-dev/pull/32

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nashaath** [comment]
Fixed via https://github.com/wso2/docs-choreo-dev/pull/50
